### ISSUE TITLE
login works fine but self.job_search() has issue may be linked got some updates.

### ISSUE THREAD

**Issue by kanakapalli** [coding-ai/EasyApply-Linkedin#4]
Traceback (most recent call last):
  File ".\main.py", line 179, in <module>
    bot.apply()
  File ".\main.py", line 164, in apply
    self.job_search()
  File ".\main.py", line 42, in job_search
    jobs_link = self.driver.find_element_by_link_text('Jobs')
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Jobs"}   
  (Session info: chrome=83.0.4103.116)

**Comment by solcyborg** [comment]
You need a wait time, it's trying to find it before it has time to load

**Comment by coding-ai** [comment]
LinkedIn is constantly changing their website to avoid bots. This issue is totally normal. Due to this, I am not maintaining the code - I decided to make a YouTube video to explain how to build this program https://www.youtube.com/watch?v=6plKL95a134
You can watch how I get the different elements in this video and you just need to change a couple of lines of code, depending on the current elements that LinkedIn has on the website. 
Thanks!
